{
 "title": "K3s Pi Cluster Monitor",
 "description": "Custom dashboard for K3s cluster with Pi Zero 2W",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Connections",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Least CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "min",
   "targets": [
    {
     "expr": "sort_desc(min(avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance)))",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Min Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Min Mem",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (pod)(delta(kube_pod_container_status_restarts_total[15m]) > 0))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total[5m])) by (pod, namespace)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Pods Running Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{}) by (phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "kubelet_running_pod_count{kubernetes_io_role =~ \".*node.*\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Load 1m",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}}"
    }
   ]
  },
  {
   "title": "CPU Idle Avg",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node Storage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "min(node_filesystem_avail_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}/node_filesystem_size_bytes{mountpoint!~\".*(serviceaccount|proc|sys).*\", device!=\"overlay\"}) by (device, instance)",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}}"
    }
   ]
  },
  {
   "title": "Disk IO s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[2m])",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}} {{device}}"
    }
   ]
  },
  {
   "title": "Top 5 Memory Intense Pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (pod, namespace) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}))",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "TOP CPU Containers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[5m]))",
     "legendFormat": "{{ container_name }} in {{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pi Zero Memory %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (node_memory_MemAvailable_bytes{instance=~\".*pi.*\"} / node_memory_MemTotal_bytes{instance=~\".*pi.*\"} * 100)",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}}"
    }
   ]
  },
  {
   "title": "Pi Zero WiFi Signal",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_wifi_station_signal_dbm{instance=~\".*pi.*\"}",
     "legendFormat": "{{instance | split(\":\") | first | split(\".\") | first}}"
    }
   ]
  },
  {
   "title": "Top Memory Consumers by Node",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(15, sum by (pod, namespace) (container_memory_working_set_bytes{container!=\"\",container!=\"POD\"}) * on(pod, namespace) group_left(node) kube_pod_info)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}